name: React Frontend

on:
  push:
    branches: [ dev ]
    paths: 'frontend/**'
  pull_request:
    branches: [ dev ]
    paths: 'frontend/**'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Typescript Checks
      working-directory: ./frontend
      run: npm run tsc

    - name: Lint Checks
      working-directory: ./frontend
      run: npm run lint

    - name: Style Lint Checks
      working-directory: ./frontend
      run: npm run stylelint
